TestCaseName:           "TbStream_MultipleDriversTransmitter1"
TestSuiteName:          "StreamTransactionPkg"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbStream_MultipleDriversTransmitter1"
GenericNames:           ""
TestSuiteDirectory:    "reports/StreamTransactionPkg"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/StreamTransactionPkg/TbStream_MultipleDriversTransmitter1_alerts.yml"
CovYamlFile:           "reports/StreamTransactionPkg/TbStream_MultipleDriversTransmitter1_cov.yml"
ScoreboardFiles:       "reports/StreamTransactionPkg/TbStream_MultipleDriversTransmitter1_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/StreamTransactionPkg/TbStream_MultipleDriversTransmitter1.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
