-- This file is autogenerated by CreateOsvvmScriptSettingsPkg
package body OsvvmScriptSettingsPkg is
  constant OSVVM_HOME_DIRECTORY         : string := "C:/OsvvmLibraries" ;
  constant OSVVM_RAW_OUTPUT_DIRECTORY   : string := "" ;
  constant OSVVM_BASE_OUTPUT_DIRECTORY  : string := "" ;
  constant OSVVM_BUILD_YAML_FILE        : string := "OsvvmRun.yml" ;
  constant OSVVM_TRANSCRIPT_YAML_FILE   : string := "OSVVM_transcript.yml" ;
  constant OSVVM_REVISION               : string := "2024.05" ;
  constant OSVVM_SETTINGS_REVISION      : string := "2024.05" ;
end package body OsvvmScriptSettingsPkg ;
