TestCaseName:           "Tb_xMii1"
TestSuiteName:          "Ethernet"
BuildName:              "OsvvmLibraries_RunErrorTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "Tb_xMii1"
GenericNames:           ""
TestSuiteDirectory:    "reports/Ethernet"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/Ethernet/Tb_xMii1_alerts.yml"
CovYamlFile:           ""
ScoreboardFiles:       "reports/Ethernet/Tb_xMii1_sb_int.yml reports/Ethernet/Tb_xMii1_sb_slv.yml"
ScoreboardNames:       "int slv"
TranscriptFiles:       "results/Ethernet/Tb_xMii1.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunErrorTestsWithCoverage_code_cov/index.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
