TestCaseName:           "Tb_xMii1"
TestSuiteName:          "Ethernet"
BuildName:              "OsvvmLibraries_RunErrorTestsWithCoverage"
GenericList:            "{MII_INTERFACE RMII} {MII_BPS BPS_100M}"
TestCaseFileName:       "Tb_xMii1_MII_INTERFACE_RMII_MII_BPS_BPS_100M"
GenericNames:           "_MII_INTERFACE_RMII_MII_BPS_BPS_100M"
TestSuiteDirectory:    "reports/Ethernet"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/Ethernet/Tb_xMii1_MII_INTERFACE_RMII_MII_BPS_BPS_100M_alerts.yml"
CovYamlFile:           ""
ScoreboardFiles:       "reports/Ethernet/Tb_xMii1_MII_INTERFACE_RMII_MII_BPS_BPS_100M_sb_int.yml reports/Ethernet/Tb_xMii1_MII_INTERFACE_RMII_MII_BPS_BPS_100M_sb_slv.yml"
ScoreboardNames:       "int slv"
TranscriptFiles:       "results/Ethernet/Tb_xMii1_MII_INTERFACE_RMII_MII_BPS_BPS_100M.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunErrorTestsWithCoverage_code_cov/index.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
