TestCaseName:           "TbUart_SendGet1"
TestSuiteName:          "Uart"
BuildName:              "OsvvmLibraries_RunErrorTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbUart_SendGet1"
GenericNames:           ""
TestSuiteDirectory:    "reports/Uart"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/Uart/TbUart_SendGet1_alerts.yml"
CovYamlFile:           ""
ScoreboardFiles:       "reports/Uart/TbUart_SendGet1_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/Uart/TbUart_SendGet1.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunErrorTestsWithCoverage_code_cov/index.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
