version: 2

submodules:
  include: []

build:
  image: latest

python:
  version: 3.8
  install:
    - requirements: requirements.txt

sphinx:
  builder: html
  configuration: conf.py

formats:
  - pdf
  - epub

