TestCaseName:           "TbStream_ReleaseAcquireReceiver1"
TestSuiteName:          "StreamTransactionArrayPkg"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbStream_ReleaseAcquireReceiver1"
GenericNames:           ""
TestSuiteDirectory:    "reports/StreamTransactionArrayPkg"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/StreamTransactionArrayPkg/TbStream_ReleaseAcquireReceiver1_alerts.yml"
CovYamlFile:           "reports/StreamTransactionArrayPkg/TbStream_ReleaseAcquireReceiver1_cov.yml"
ScoreboardFiles:       "reports/StreamTransactionArrayPkg/TbStream_ReleaseAcquireReceiver1_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/StreamTransactionArrayPkg/TbStream_ReleaseAcquireReceiver1.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
