TestCaseName:           "TbAxi4_ReadyTimingSubordinate"
TestSuiteName:          "Axi4Full"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbAxi4_ReadyTimingSubordinate"
GenericNames:           ""
TestSuiteDirectory:    "reports/Axi4Full"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/Axi4Full/TbAxi4_ReadyTimingSubordinate_alerts.yml"
CovYamlFile:           "reports/Axi4Full/TbAxi4_ReadyTimingSubordinate_cov.yml"
ScoreboardFiles:       "reports/Axi4Full/TbAxi4_ReadyTimingSubordinate_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/Axi4Full/TbAxi4_ReadyTimingSubordinate.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
