TestCaseName:           "TbAb_Interrupt2"
TestSuiteName:          "InterruptHandler_Gen"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbAb_Interrupt2"
GenericNames:           ""
TestSuiteDirectory:    "reports/InterruptHandler_Gen"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/InterruptHandler_Gen/TbAb_Interrupt2_alerts.yml"
CovYamlFile:           "reports/InterruptHandler_Gen/TbAb_Interrupt2_cov.yml"
ScoreboardFiles:       "reports/InterruptHandler_Gen/TbAb_Interrupt2_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/InterruptHandler_Gen/TbAb_Interrupt2.log"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
