TestCaseName:           "TbStream_ByteHandling1"
TestSuiteName:          "AxiStream_VTI"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbStream_ByteHandling1"
GenericNames:           ""
TestSuiteDirectory:    "reports/AxiStream_VTI"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/AxiStream_VTI/TbStream_ByteHandling1_alerts.yml"
CovYamlFile:           "reports/AxiStream_VTI/TbStream_ByteHandling1_cov.yml"
ScoreboardFiles:       "reports/AxiStream_VTI/TbStream_ByteHandling1_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/AxiStream_VTI/TbStream_ByteHandling1.log"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
