TestCaseName:           "TbStream_AxiTxValidDelay1"
TestSuiteName:          "AxiStream"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbStream_AxiTxValidDelay1"
GenericNames:           ""
TestSuiteDirectory:    "reports/AxiStream"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/AxiStream/TbStream_AxiTxValidDelay1_alerts.yml"
CovYamlFile:           "reports/AxiStream/TbStream_AxiTxValidDelay1_cov.yml"
ScoreboardFiles:       "reports/AxiStream/TbStream_AxiTxValidDelay1_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/AxiStream/TbStream_AxiTxValidDelay1.log"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
