TestCaseName:           "Tb_xMii1"
TestSuiteName:          "Ethernet"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            "{MII_INTERFACE RGMII} {MII_BPS BPS_1G}"
TestCaseFileName:       "Tb_xMii1_MII_INTERFACE_RGMII_MII_BPS_BPS_1G"
GenericNames:           "_MII_INTERFACE_RGMII_MII_BPS_BPS_1G"
TestSuiteDirectory:    "reports/Ethernet"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/Ethernet/Tb_xMii1_MII_INTERFACE_RGMII_MII_BPS_BPS_1G_alerts.yml"
CovYamlFile:           ""
ScoreboardFiles:       "reports/Ethernet/Tb_xMii1_MII_INTERFACE_RGMII_MII_BPS_BPS_1G_sb_int.yml reports/Ethernet/Tb_xMii1_MII_INTERFACE_RGMII_MII_BPS_BPS_1G_sb_slv.yml"
ScoreboardNames:       "int slv"
TranscriptFiles:       "results/Ethernet/Tb_xMii1_MII_INTERFACE_RGMII_MII_BPS_BPS_1G.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
