TestCaseName:           "TbUart_SingleProcess_1"
TestSuiteName:          "Uart"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbUart_SingleProcess_1"
GenericNames:           ""
TestSuiteDirectory:    "reports/Uart"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/Uart/TbUart_SingleProcess_1_alerts.yml"
CovYamlFile:           ""
ScoreboardFiles:       "reports/Uart/TbUart_SingleProcess_1_sb_slv.yml reports/Uart/TbUart_SingleProcess_1_sb_TbUart_SingleProcess_1_sb_Uart.yml.yml"
ScoreboardNames:       "slv TbUart_SingleProcess_1_sb_Uart.yml"
TranscriptFiles:       "results/Uart/SingleProcess_1.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
