TestCaseName:           "TbAxi4_SubordinateReadWriteAsync2"
TestSuiteName:          "AddressBusTransactionPkg"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbAxi4_SubordinateReadWriteAsync2"
GenericNames:           ""
TestSuiteDirectory:    "reports/AddressBusTransactionPkg"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/AddressBusTransactionPkg/TbAxi4_SubordinateReadWriteAsync2_alerts.yml"
CovYamlFile:           "reports/AddressBusTransactionPkg/TbAxi4_SubordinateReadWriteAsync2_cov.yml"
ScoreboardFiles:       "reports/AddressBusTransactionPkg/TbAxi4_SubordinateReadWriteAsync2_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/AddressBusTransactionPkg/TbAxi4_SubordinateReadWriteAsync2.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
