TestCaseName:           "TbAxi4_RandomReadWrite"
TestSuiteName:          "Axi4Lite"
BuildName:              "OsvvmLibraries_RunErrorTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbAxi4_RandomReadWrite"
GenericNames:           ""
TestSuiteDirectory:    "reports/Axi4Lite"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/Axi4Lite/TbAxi4_RandomReadWrite_alerts.yml"
CovYamlFile:           "reports/Axi4Lite/TbAxi4_RandomReadWrite_cov.yml"
ScoreboardFiles:       "reports/Axi4Lite/TbAxi4_RandomReadWrite_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/Axi4Lite/TbAxi4_RandomReadWrite.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunErrorTestsWithCoverage_code_cov/index.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
