TestCaseName:           "TbModelParameters1"
TestSuiteName:          "ModelParams"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbModelParameters1"
GenericNames:           ""
TestSuiteDirectory:    "reports/ModelParams"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/ModelParams/TbModelParameters1_alerts.yml"
CovYamlFile:           ""
ScoreboardFiles:       ""
ScoreboardNames:       ""
TranscriptFiles:       ""
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
