TestCaseName:           "TbStream_SendGetDemo1"
TestSuiteName:          "AxiStream"
BuildName:              "OsvvmLibraries_RunErrorTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbStream_SendGetDemo1"
GenericNames:           ""
TestSuiteDirectory:    "reports/AxiStream"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/AxiStream/TbStream_SendGetDemo1_alerts.yml"
CovYamlFile:           "reports/AxiStream/TbStream_SendGetDemo1_cov.yml"
ScoreboardFiles:       "reports/AxiStream/TbStream_SendGetDemo1_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/AxiStream/TbStream_SendGetDemo1.log"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunErrorTestsWithCoverage_code_cov/index.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
