TestCaseName:           "TbVideoBus_SendGet"
TestSuiteName:          "VideoBus"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbVideoBus_SendGet"
GenericNames:           ""
TestSuiteDirectory:    "reports/VideoBus"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/VideoBus/TbVideoBus_SendGet_alerts.yml"
CovYamlFile:           ""
ScoreboardFiles:       "reports/VideoBus/TbVideoBus_SendGet_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/VideoBus/TbVideoBus_SendGet.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
