TestCaseName:           "TbAxi4_MemoryBurstPattern1"
TestSuiteName:          "Axi4Full"
BuildName:              "OsvvmLibraries_RunErrorTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbAxi4_MemoryBurstPattern1"
GenericNames:           ""
TestSuiteDirectory:    "reports/Axi4Full"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/Axi4Full/TbAxi4_MemoryBurstPattern1_alerts.yml"
CovYamlFile:           "reports/Axi4Full/TbAxi4_MemoryBurstPattern1_cov.yml"
ScoreboardFiles:       "reports/Axi4Full/TbAxi4_MemoryBurstPattern1_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/Axi4Full/TbAxi4_MemoryBurstPattern1.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunErrorTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunErrorTestsWithCoverage_code_cov/index.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
