TestCaseName:           "TbAxi4_AlertLogIDManager"
TestSuiteName:          "AddressBusTransactionArrayPkg"
BuildName:              "OsvvmLibraries_RunAllTestsWithCoverage"
GenericList:            ""
TestCaseFileName:       "TbAxi4_AlertLogIDManager"
GenericNames:           ""
TestSuiteDirectory:    "reports/AddressBusTransactionArrayPkg"
RequirementsYamlFile:  ""
AlertYamlFile:         "reports/AddressBusTransactionArrayPkg/TbAxi4_AlertLogIDManager_alerts.yml"
CovYamlFile:           "reports/AddressBusTransactionArrayPkg/TbAxi4_AlertLogIDManager_cov.yml"
ScoreboardFiles:       "reports/AddressBusTransactionArrayPkg/TbAxi4_AlertLogIDManager_sb_slv.yml"
ScoreboardNames:       "slv"
TranscriptFiles:       "results/AddressBusTransactionArrayPkg/TbAxi4_AlertLogIDManager.txt"
OsvvmSettingsInfo:
  BaseDirectory:        ""
  ReportsSubdirectory:  "reports"
  CssSubdirectory:      "reports"
  SimulationLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage.log"
  SimulationHtmlLogFile: "logs/OsvvmLibraries_RunAllTestsWithCoverage_log.html"
  CssPngSourceDirectory:   "C:/OsvvmLibraries/Scripts"
  RequirementsSubdirectory: ""
  CoverageSubdirectory:    "CodeCoverage/OsvvmLibraries_RunAllTestsWithCoverage_code_cov.html"
  Report2CssFiles: "reports/CssOsvvmStyle.css"
  Report2PngFile:  "reports/OsvvmLogo.png"
